### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#36]

**Comment by arahuja** [comment]
An FYI, all but 4 of the tests seem to pass on py3, except for 4 (which seem documented to not pass?)

```
======================================================================
ERROR: test_data_sample.test_tf_multiple_samples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arahuja/anaconda/envs/py34/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 39, in test_tf_multiple_samples
    _test(data_tf, 2, _assert_eq_tf)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 27, in _test
    samples1 = _sample_onepass(data, n_samples)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 12, in _sample_onepass
    for _ in range(data.N / n_samples):
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: test_data_sample.test_ndarray_single_sample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arahuja/anaconda/envs/py34/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 43, in test_ndarray_single_sample
    _test(data_ndarray, 1, _assert_eq_ndarray)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 27, in _test
    samples1 = _sample_onepass(data, n_samples)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 12, in _sample_onepass
    for _ in range(data.N / n_samples):
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: test_data_sample.test_ndarray_multiple_samples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arahuja/anaconda/envs/py34/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 47, in test_ndarray_multiple_samples
    _test(data_ndarray, 2, _assert_eq_ndarray)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 27, in _test
    samples1 = _sample_onepass(data, n_samples)
  File "/Users/arahuja/src/edward/tests/test_data_sample.py", line 12, in _sample_onepass
    for _ in range(data.N / n_samples):
TypeError: 'float' object cannot be interpreted as an integer

----------------------------------------------------------------------
Ran 100 tests in 314.228s

FAILED (errors=4)
```

Were there other python 3 issues? I'm actually having issues running things on python 2, but may be my setup there I don't use that often anymore

**Comment by dustinvtran** [comment]
Hi @arahuja, I haven't looked too closely at the python 3 compatibility. I suspect there's more issues beyond just the unit tests (it doesn't cover much of the code base). We plan to use something like 2to3 and then from that point force all code to be compatible with both versions.
