### ISSUE TITLE
Copied recursive graphs cannot be differentiated

### ISSUE THREAD

**Issue by chmp** [blei-lab/edward#525]
After copying the graph of recursive variables, it cannot be differentiated. A Minimal example is:

```python
In [1]: import edward as ed

In [2]: import tensorflow as tf

In [3]: get_grads = lambda tensor: tf.gradients(tensor, [v._ref() for v in ed.get_variables(tensor)])

In [4]: cumsum = lambda tensor: tf.scan(lambda a, x: a + x, tensor)

In [5]: a = tf.Variable([1.0, 2.0, 3.0])

In [6]: get_grads(2 * a)
Out[6]: [<tf.Tensor 'gradients_2/mul_2_grad/Reshape_1:0' shape=(3,) dtype=float32>]

In [7]: get_grads(ed.copy(2 * a))
Out[7]: [<tf.Tensor 'gradients_3/copied/mul_3_grad/Reshape_1:0' shape=(3,) dtype=float32>]

In [8]: get_grads(cumsum(a))
Out[8]: [<tf.Tensor 'gradients_4/scan/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3:0' shape=(3,) dtype=float32>]

In [9]: get_grads(ed.copy(cumsum(a)))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-713dbebd9b76> in <module>()
----> 1 get_grads(ed.copy(cumsum(a)))

<ipython-input-7-a19aa9ea108c> in <lambda>(tensor)
----> 1 get_grads = lambda tensor: tf.gradients(tensor, [v._ref() for v in ed.get_variables(tensor)])

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method)
    392     pending_count, loop_state = _PendingCount(ops.get_default_graph(), to_ops,
    393                                               from_ops,
--> 394                                               colocate_gradients_with_ops)
    395 
    396     # Iterate over the collected ops.

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py in _PendingCount(graph, to_ops, from_ops, colocate_gradients_with_ops)
    184   # 'loop_state' is None if there are no while loops.
    185   loop_state = control_flow_ops.MaybeCreateControlFlowState(
--> 186       between_op_list, between_ops, colocate_gradients_with_ops)
    187 
    188   # Initialize pending count for between ops.

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in MaybeCreateControlFlowState(between_op_list, between_ops, colocate_gradients_with_ops)
   1293           loop_state.AddWhileContext(op, between_op_list, between_ops)
   1294       else:
-> 1295         loop_state.AddWhileContext(op, between_op_list, between_ops)
   1296   return loop_state
   1297 

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in AddWhileContext(self, op, between_op_list, between_ops)
   1102     if grad_state is None:
   1103       # This is a new while loop so create a grad state for it.
-> 1104       outer_forward_ctxt = forward_ctxt.outer_context
   1105       if outer_forward_ctxt:
   1106         outer_forward_ctxt = outer_forward_ctxt.GetWhileContext()

AttributeError: 'NoneType' object has no attribute 'outer_context'
````

At least on difference is the missing `_control_flow_context`:

```python
In [10]: get_exit_context = lambda tensor: tensor.op.inputs[2].op._control_flow_context

In [11]: get_exit_context(cumsum(a))
Out[11]: <tensorflow.python.ops.control_flow_ops.WhileContext at 0x11c87e160>

In [12]: get_exit_context(ed.copy(cumsum(a))) is None
Out[12]: True
```

**Comment by chmp** [comment]
Update: I started looking into repairing the control flow context after the fact. You can find the current implementation [here](https://gist.github.com/chmp/aa3036d0fe262aca0530a3b6fd223cf5). 

Now `tf.gradients` works, but evaluating its result throws an exception:

```python
grad = get_gradients(copied)
ed.get_session().run(grad)
```
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1021     try:
-> 1022       return fn(*args)
   1023     except errors.OpError as e:

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1003                                  feed_dict, fetch_list, target_list,
-> 1004                                  status, run_metadata)
   1005 

/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in raise_exception_on_not_ok_status()
    468           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 469           pywrap_tensorflow.TF_GetCode(status))
    470   finally:

InvalidArgumentError: The node 'gradients_4/copied/scan_5/while/add_grad/BroadcastGradientArgs/StackPush_1' has inputs from different frames. The input 'gradients_4/copied/scan_5/while/add_grad/Shape_1' is in frame 'gradients_4/copied/scan_5/while/scan_5/while/'. The input 'gradients_4/copied/scan_5/while/add_grad/BroadcastGradientArgs/RefEnter_3' is in frame 'copied/scan_5/while/scan_5/while/'.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-166-b87982395a3e> in <module>()
      1 grad = get_gradients(copied)
----> 2 ed.get_session().run(grad)

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    765     try:
    766       result = self._run(None, fetches, feed_dict, options_ptr,
--> 767                          run_metadata_ptr)
    768       if run_metadata:
    769         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    963     if final_fetches or final_targets:
    964       results = self._do_run(handle, final_targets, final_fetches,
--> 965                              feed_dict_string, options, run_metadata)
    966     else:
    967       results = []

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1013     if handle is None:
   1014       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1015                            target_list, options, run_metadata)
   1016     else:
   1017       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1033         except KeyError:
   1034           pass
-> 1035       raise type(e)(node_def, op, message)
   1036 
   1037   def _extend_graph(self):

InvalidArgumentError: The node 'gradients_4/copied/scan_5/while/add_grad/BroadcastGradientArgs/StackPush_1' has inputs from different frames. The input 'gradients_4/copied/scan_5/while/add_grad/Shape_1' is in frame 'gradients_4/copied/scan_5/while/scan_5/while/'. The input 'gradients_4/copied/scan_5/while/add_grad/BroadcastGradientArgs/RefEnter_3' is in frame 'copied/scan_5/while/scan_5/while/'.
```

**Comment by dustinvtran** [comment]
I tried making progress in a branch, `bugfix/issue-525`. You can see a diff to master here: https://github.com/blei-lab/edward/compare/bugfix/issue-525.

In particular, I added a minimal example in `test_copy.py` that should work but doesn't. As you note, the difficulty is how to copy contexts. Working off `ctx.from_proto(ctx.to_proto(), ...)` has some success. Things still need to be changed such as `ctx._values`. I'm also not sure if we need to handle all that grad loop state stuff; in general TensorFlow's [`control_flow_ops.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/control_flow_ops.py) is mysterious to me.

**Comment by chmp** [comment]
Cool, that there is still progress. I tried you branch, but I get:

```
    def _copy_context(ctx, context_matches):
      if ctx is None:
        return None
      elif ctx in context_matches:
        return context_matches[ctx]
    
      loop_exits = []
      for tensor in ctx.loop_exits:
>       loop_exits.append(copy(tensor, dict_swap, scope, True, copy_q))
E       NameError: name 'dict_swap' is not defined
```

**Comment by dustinvtran** [comment]
Oh, originally I wrote the function inside `copy`. I guess that's still needed to do the scoping properly.

**Comment by chmp** [comment]
For me 

```
diff --git a/edward/util/random_variables.py b/edward/util/random_variables.py
index cff24b89..0f946935 100644
--- a/edward/util/random_variables.py
+++ b/edward/util/random_variables.py
@@ -80,7 +80,7 @@ def check_latent_vars(latent_vars):
                       "dtype: {}, {}".format(key.dtype, value.dtype))
 
 
-def _copy_context(ctx, context_matches):
+def _copy_context(ctx, context_matches, dict_swap, scope, copy_q):
   if ctx is None:
     return None
   elif ctx in context_matches:
@@ -96,7 +96,7 @@ def _copy_context(ctx, context_matches):
   for string in ctx._values:
     values.add(scope + '/' + string)
 
-  _copy_context(ctx.outer_context, context_matches)
+  _copy_context(ctx.outer_context, context_matches, dict_swap, scope, copy_q)
 
   # TODO is control_flow_context necessary? if so, also check out ctx.Enter()/Exit()
   # prev = graph._get_control_flow_context()
@@ -346,7 +346,7 @@ def copy(org_instance, dict_swap=None, scope="copied",
       new_op._add_input(elem)
 
     # Copy the control flow context.
-    control_flow_context = _copy_context(op._get_control_flow_context(), {})
+    control_flow_context = _copy_context(op._get_control_flow_context(), {}, dict_swap, scope, copy_q)
     new_op._set_control_flow_context(control_flow_context)
 
     # Use Graph's private methods to add the op, following
```

did the trick.

**Comment by jna29** [comment]
I still get this problem after using these changes.

I create a ``KLqp`` with ``latent_vars = model_to_variational_vars`` where this is a dictionary similar to that in the ``bayesian_nn.py`` example and ``data = {p: m}`` where ``p = Normal(loc=p, scale=0.001*tf.ones_like(p))`` (``p`` is of shape ``(?, N)``) and ``m`` is a ``tf.Tensor`` with the same shape as ``p``. Both ``p`` and ``m`` are computed through separate graphs that each contain one or more ``tf.map_fn`` operations.

I included this branch (https://github.com/blei-lab/edward/compare/bugfix/issue-525) and I think the failure comes from the ``ctx.from_proto(ctx.to_proto(), ...)`` line. More specifically, the ``init_from_proto`` for ``WhileContext`` in ``control_flow_ops.py`` returns a ``KeyError`` for one of the ``g.as_graph_element`` lines. This then means that ``_copy_context`` will return ``None`` (due to the ``try ... except``) and so the context is not copied.

**Comment by davharris** [comment]
Wow, this sounds complicated. Until a fix is ready, I have two questions:

* What's the recommended way to call a function repeatedly on different inputs (assuming we need to backpropagate through them)? Is there a better option than copy-pasting the function?

* Would it be possible to catch this error earlier and print an informative error message along the lines of `Edward does not yet support differentiating through this control op`? This seems to be a common issue for users (there are 5 other issues referencing this one).

**Comment by coryshain** [comment]
I think I've run into this problem, too. I'm new to edward and I have a working tensorflow network that I'm trying to reimplement in edward, but it crucially involves a `tf.map_fn` call on the inputs because I have to gather from tensors in different ways depending on features of each training datapoint. When I cut out `tf.map_fn` I can run HMC inference (but then the network doesn't work as designed), but when I include it the inference call crashes with the following trace. I'm using edward 1.3.4.

```
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    cmap=p.cmap
  File "/media/cory/Windows/Users/corys/AppData/Local/lxss/home/shain/dtsr/dtsr/bdtsr.py", line 423, in fit
    inference.run()
  File "/media/cory/Windows/Users/corys/AppData/Local/lxss/home/shain/neural-segmentation/src/edward/edward/inferences/inference.py", line 123, in run
    self.initialize(*args, **kwargs)
  File "/media/cory/Windows/Users/corys/AppData/Local/lxss/home/shain/neural-segmentation/src/edward/edward/inferences/hmc.py", line 64, in initialize
    return super(HMC, self).initialize(*args, **kwargs)
  File "/media/cory/Windows/Users/corys/AppData/Local/lxss/home/shain/neural-segmentation/src/edward/edward/inferences/monte_carlo.py", line 101, in initialize
    self.train = self.build_update()
  File "/media/cory/Windows/Users/corys/AppData/Local/lxss/home/shain/neural-segmentation/src/edward/edward/inferences/hmc.py", line 91, in build_update
    self.n_steps)
  File "/media/cory/Windows/Users/corys/AppData/Local/lxss/home/shain/neural-segmentation/src/edward/edward/inferences/hmc.py", line 161, in leapfrog
    grad_log_joint = tf.gradients(log_joint(z_new), list(six.itervalues(z_new)))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 490, in gradients
    colocate_gradients_with_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 191, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1310, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1119, in AddWhileContext
    outer_forward_ctxt = forward_ctxt.outer_context
AttributeError: 'NoneType' object has no attribute 'outer_context'
```
