### ISSUE TITLE
TypeError: First parent class declared for Bernoulli must be Distribution, but saw 'RandomVariable'

### ISSUE THREAD

**Issue by mingwugmail** [blei-lab/edward#600]
$ sudo pip2 install edward

Successfully installed edward-1.2.4

$ python MDN_Edward_Keras_TF.py 
Traceback (most recent call last):
  File "MDN_Edward_Keras_TF.py", line 45, in <module>
    import edward as ed
  File "/usr/local/lib/python2.7/dist-packages/edward/__init__.py", line 5, in <module>
    from edward import criticisms
  File "/usr/local/lib/python2.7/dist-packages/edward/criticisms/__init__.py", line 5, in <module>
    from edward.criticisms.evaluate import *
  File "/usr/local/lib/python2.7/dist-packages/edward/criticisms/evaluate.py", line 9, in <module>
    from edward.models import RandomVariable
  File "/usr/local/lib/python2.7/dist-packages/edward/models/__init__.py", line 5, in <module>
    from edward.models.dirichlet_process import *
  File "/usr/local/lib/python2.7/dist-packages/edward/models/dirichlet_process.py", line 8, in <module>
    from edward.models.random_variables import Bernoulli, Beta
  File "/usr/local/lib/python2.7/dist-packages/edward/models/random_variables.py", line 20, in <module>
    _globals[_name] = type(_name, (RandomVariable, _candidate), params)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distributions/python/ops/distribution.py", line 138, in __new__
    "Distribution, but saw '%s'" % (classname, base.__name__))
TypeError: First parent class declared for Bernoulli must be Distribution, but saw 'RandomVariable'

**Comment by mingwugmail** [comment]
pip install -e "git+https://github.com/blei-lab/edward.git#egg=edward"

same error

**Comment by dustinvtran** [comment]
You need to use TensorFlow >= 1.0.0a0. http://edwardlib.org/troubleshooting

Also see https://github.com/blei-lab/edward/issues/315. Closing as duplicate issue.
