### ISSUE TITLE
Cannot calculate gradients with keras Dropout or BatchNormalization layers

### ISSUE THREAD

**Issue by JohnReid** [blei-lab/edward#602]
I was trying to rewrite the `vae_convolutional.py` example to use keras instead of tf.slim but edward seems to have a problem calculating the gradients. I replace `inference_network()` with:

```
def inference_network(x):
  """Inference network to parameterize variational model. It takes
  data as input and outputs the variational parameters.

  mu, sigma = neural_network(x)
  """
  from keras.models import Sequential
  from keras.layers.core import Dropout, Flatten, Activation, Dense
  from keras.layers.convolutional import Conv2D
  from keras.layers.normalization import BatchNormalization
  net = Sequential([
      Conv2D( 32, 5, padding='same', strides=2, input_shape=(28, 28, 1)),
      # BatchNormalization(),
      Activation('elu'),
      Conv2D( 64, 5, padding='same', strides=2),
      # BatchNormalization(),
      Activation('elu'),
      Conv2D(128, 5, padding='valid'),
      # BatchNormalization(),
      Activation('elu'),
      Dropout(.1),
      Flatten(),
      Dense(D * 2),
    ])

  params = net(tf.reshape(x, [M, 28, 28, 1]))
  mu = params[:, :D]
  sigma = tf.nn.softplus(params[:, D:])
  return mu, sigma
```
But whenever I include a `BatchNormalization` or `Dropout` layer in the keras model I get the following error when initialising the `ed.KLqp` object. Does this look like an edward or a keras problem? AFAICT the keras code I have matches the tf.slim code well.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/john/Dev/edward/examples/vae_convolutional.py in <module>()
    142 inference = ed.KLqp({z: qz}, data)
    143 optimizer = tf.train.AdamOptimizer(0.01, epsilon=1.0)
--> 144 inference.initialize(optimizer=optimizer)
    145
    146 hidden_rep = tf.sigmoid(logits)

/home/john/Dev/edward/edward/inferences/klqp.py in initialize(self, n_samples, kl_scaling, *args, **kwargs)
    110     self.n_samples = n_samples
    111     self.kl_scaling = kl_scaling
--> 112     return super(KLqp, self).initialize(*args, **kwargs)
    113
    114   def build_loss_and_gradients(self, var_list):

/home/john/Dev/edward/edward/inferences/variational_inference.py in initialize(self, optimizer, var_list, use_prettytensor, *args, **kwargs)
     71       var_list = list(var_list)
     72
---> 73     self.loss, grads_and_vars = self.build_loss_and_gradients(var_list)
     74
     75     if optimizer is None:

/home/john/Dev/edward/edward/inferences/klqp.py in build_loss_and_gradients(self, var_list)
    145     if is_reparameterizable:
    146       if is_analytic_kl:
--> 147         return build_reparam_kl_loss_and_gradients(self, var_list)
    148       # elif is_analytic_entropy:
    149       #    return build_reparam_entropy_loss_and_gradients(self, var_list)

/home/john/Dev/edward/edward/inferences/klqp.py in build_reparam_kl_loss_and_gradients(inference, var_list)
    471   loss = -(tf.reduce_mean(p_log_lik) - kl)
    472
--> 473   grads = tf.gradients(loss, [v._ref() for v in var_list])
    474   grads_and_vars = list(zip(grads, var_list))
    475   return loss, grads_and_vars

/home/john/Dev/edward/venv/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method)
    472                 out_grads[i] = loop_state.ZerosLike(op, i)
    473               else:
--> 474                 out_grads[i] = control_flow_ops.ZerosLikeOutsideLoop(op, i)
    475           with ops.name_scope(op.name + "_grad"):
    476             # pylint: disable=protected-access

/home/john/Dev/edward/venv/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in ZerosLikeOutsideLoop(op, index)
   1301   else:
   1302     op_ctxt = op._get_control_flow_context()
-> 1303     pred = op_ctxt.pred
   1304     branch = op_ctxt.branch
   1305     switch_val = switch(op.inputs[0], pred)[1 - branch]

AttributeError: 'NoneType' object has no attribute 'pred'
> /home/john/Dev/edward/venv/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py(1303)ZerosLikeOutsideLoop()
   1301   else:
   1302     op_ctxt = op._get_control_flow_context()
-> 1303     pred = op_ctxt.pred
   1304     branch = op_ctxt.branch
   1305     switch_val = switch(op.inputs[0], pred)[1 - branch]

```

**Comment by JohnReid** [comment]
I should say I want to do this in order to implement semi-supervised learning a la Kingma, Rezende, Welling and Mohamed in which I need to reuse the network for various different inputs (labelled and unlabelled examples). AFAICT slim doesn't support reuse of the network  whereas it is straightforward with keras.

**Comment by dustinvtran** [comment]
I tracked down the issue. It ultimately comes from #525. Keras' BatchNormalization and Dropout layers use control flow to perform different ops depending on `K.learning_phase()`. Edward's `copy` utility function doesn't successfully handle them, which in turn causes the error in `ed.KLqp`.
```python
import edward as ed
import tensorflow as tf
from keras.layers import Dropout

x = tf.placeholder(tf.float32, [1, 5])
y = Dropout(0.1)(x)

grad = tf.gradients(y, [y])  # succeeds

y_copy = ed.copy(y)
grads_copy = tf.gradients(y_copy, [x])  # fails
```
```
Traceback (most recent call last):
  File "vae.py", line 14, in <module>
    grads_copy = tf.gradients(y_copy, [x])
  File "/Users/dvt/Envs/venv/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 474, in gradients
    out_grads[i] = control_flow_ops.ZerosLikeOutsideLoop(op, i)
  File "/Users/dvt/Envs/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1303, in ZerosLikeOutsideLoop
    pred = op_ctxt.pred
AttributeError: 'NoneType' object has no attribute 'pred'
```

**Comment by JohnReid** [comment]
Thanks for investigating. From the looks of it there is no quick fix.

BTW did you mean
`grad = tf.gradients(y, [x])  # succeeds`
instead of
`grad = tf.gradients(y, [y])  # succeeds`

I shall have to look a bit more closely at tensorflow slim but AFAICT there is no easy way to apply networks defined in slim on more than one tensor. I find slim's documentation a little sparse.

**Comment by dustinvtran** [comment]
> BTW did you mean
> grad = tf.gradients(y, [x]) # succeeds
> instead of
> grad = tf.gradients(y, [y]) # succeeds

oops, that is correct.

**Comment by ErmiaAzarkhalili** [comment]
Hi @dustinvtran , Could you please help us resolve this issue and let us know how we can utilize BatchNormalization and Dropout layers in keras model feeding to Edward.

**Comment by im-Kitsch** [comment]
@JohnReid Hi, John, by me when I run the convolution_vae.py it doesn't convergence but always with -log(px) < -nan, doesn it work for you?

My version is
edward 1.3.5
tensorflow 1.5.0
python 3.6.5
