### ISSUE TITLE
Unresoleved Import: cannot import distributions 'Normal', 'Categorical'

### ISSUE THREAD

**Issue by mb3647** [blei-lab/edward#614]
I was trying the following simple code in 
Eclipse+PyDev+python3.5
Edward __version__ = '1.2.4' (pip installed) 
tensorflow-gpu __version__ = '1.0.1' (pip installed)
keras __version__ =  '2.0.3'
OS = 'Windows 10'
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import edward as ed
import numpy as np
import tensorflow as tf

from edward.models import Normal

ed.set_seed(42)

# DATA
x_data = np.array([0.0] * 50)

# MODEL: Normal-Normal with known variance
mu = Normal(mu=0.0, sigma=1.0)
x = Normal(mu=tf.ones(50) * mu, sigma=1.0)
```

Normal in import is not recognized. It is showing unresolved import. 
In the source the distribution classes are not present. Maybe the auto generation is not working.
Please help. 

Thanks,
Sharif

**Comment by dustinvtran** [comment]
See the [troubleshooting](http://edwardlib.org/troubleshooting). My immediate guess is that you need to update TensorFlow.

**Comment by mb3647** [comment]
Hi Dustin,

Thanks a lot for your quick reply.

First, I tried the following 

from tensorflow.contrib.distributions import Normal

Now the PyDev recognized the import, but when I ran it the following error occurred.

Traceback (most recent call last):
  File "C:\Users\Sharif\workspace\Test\model.py", line 19, in <module>
    x = Normal(loc=tf.ones(50) * mu, scale=1.0)
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\math_ops.py", line 820, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "C:\Users\Sharif\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected float32, got <tensorflow.contrib.distributions.python.ops.normal.Normal object at 0x0000016F8DD908D0> of type 'Normal' instead.

Then I updated tensorflow-gpu to  __version__  1.1.0-rc2

And installed edward using command 

pip install -e "git+https://github.com/blei-lab/edward.git@bugfix/issue-451#egg=edward"

But the problem remains. Recognized the import but got runtime error. Same call trace.

Any other suggestions?

Thanks in advance.
Sharif

**Comment by dustinvtran** [comment]
Great! The `from tensorflow.contrib.distributions import Normal` call was just to check that this class exists. You should be using `from edward.models import Normal` which should not result in that error.

**Comment by prithagupta** [comment]
AttributeError: 'Normal' object has no attribute 'get_shape'
After importing it from tensorflow "from tensorflow.python.ops.distributions.normal import Normal"
