### ISSUE TITLE
Error importing edward 1.3.5 with tensorflow 1.7.0

### ISSUE THREAD

**Issue by bjfar** [blei-lab/edward#882]
I have tensorflow 1.7.0 built from source and installed, and it seems to work ok by itself, but I cannot import edward:

```
>>> import tensorflow
/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> print(tensorflow.__version__)
1.7.0
>>> import edward
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/edward/__init__.py", line 5, in <module>
    from edward import criticisms
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/edward/criticisms/__init__.py", line 7, in <module>
    from edward.criticisms.evaluate import *
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/edward/criticisms/evaluate.py", line 10, in <module>
    from edward.util import check_data, get_session, compute_multinomial_mode, \
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/edward/util/__init__.py", line 10, in <module>
    from edward.util.random_variables import *
  File "/home/farmer/anaconda3/envs/general/lib/python3.6/site-packages/edward/util/random_variables.py", line 15, in <module>
    from tensorflow.python.framework.ops import set_shapes_for_outputs
ImportError: cannot import name 'set_shapes_for_outputs'
```

I am on Ubuntu 16.04 LTS and using the edward version installed via pip, which appears to be 1.3.5:

```
$ pip show edward
Name: edward
Version: 1.3.5
Summary: A library for probabilistic modeling, inference, and criticism
Home-page: http://edwardlib.org
Author: Dustin Tran
Author-email: dustin@cs.columbia.edu
License: Apache License 2.0
Location: /home/farmer/anaconda3/envs/general/lib/python3.6/site-packages
Requires: six, numpy
```

I was going to try building edward from source, but the latest tagged version seems to be 1.3.5 anyway so I guess this will not help. My Python version is 3.6.4.

**Comment by dustinvtran** [comment]
Looks like the function no longer exists in TF 1.7.0. Following the commit, we may be able to just remove it in the `ed.copy` implementation (https://github.com/tensorflow/tensorflow/commit/9fc9f19428e497f3a297538059804f69996a612e#diff-66fbf57743aed7c8407bcb218db3c491L2477).

**Comment by wingsangel** [comment]
how can i commit?

**Comment by sunny1205124** [comment]
I have the same questions with you. Have you solved this question?

**Comment by hiraksarkar** [comment]
Any fix yet?

**Comment by DiegoVicen** [comment]
Having the same problem with tensorflow 1.8.0 built from source

**Comment by IanQS** [comment]
If you follow the link you'll see the discussion on what to do. I'm not sure if there's a discussion on another platform (if there is please let me know I'd love to see and contribute to solving this issue)

**Comment by larsr** [comment]
I noticed that `set_shapes_for_outputs` now (since 9fc9f19428e497f3a) seems to be called `set_shape_and_handle_data_for_outputs`

**Comment by IanQS** [comment]
Can you try running the tests? Because I'm pretty sure I tried that and it failed the copy tests

**Comment by larsr** [comment]
@IanQS yeah, I did `cd edward tests; pytest .` and got "86 failed, 240 passed, 44 warnings".  In particular "pytest util/copy_test.py" got 20 failed and 3 passed.  Alas, there are more things to take care of.

**Comment by devinbostIL** [comment]
I installed TensorFlow via pip and still got this problem.

**Comment by devinbostIL** [comment]
I created a pull request here: [https://github.com/blei-lab/edward/pull/894](https://github.com/blei-lab/edward/pull/894)

**Comment by sadatnfs** [comment]
yeah I don't think Master still has it pulled in eh

**Comment by chnynf** [comment]
Having the same issue. Is there a work around for now?

**Comment by prithagupta** [comment]
Having the same issue. Is there a work around for now?

**Comment by IanQS** [comment]
workaround is to use an older version of Tensorflow (Edward should work with it up to tf 1.6)

**Comment by frank-y-liu** [comment]
Any estimated time to get this fixed? More importantly when the fix will be released to the pip channel? I know google is releasing TF at a rapid pace. Unfortunately I can't revert back to an older version of TF simply because of Edward.

**Comment by weininghu1012** [comment]
Same issue here, any possible alternative?

**Comment by acanacar** [comment]
having the same issue.Is there any solution?

**Comment by halilbilgin** [comment]
Same issue :)

**Comment by jsevo** [comment]
same issue. unfortunately unusable atm (tf moved on, and python moved on even further)

**Comment by hani1814** [comment]
Hi, any idea when the compatibility issue with version TF>=1.7 is going to be resolved?

Many thanks

**Comment by sadatnfs** [comment]
Almost certain that development on upgrading to new TF is not gonna happen any longer since Edward is now a part of TFP

**Comment by denominations-io** [comment]
Indeed, most of the functionality has been ported to https://www.tensorflow.org/probability/. See https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/edward2/Upgrading_From_Edward_To_Edward2.md

**Comment by pranav-vempati** [comment]
Having the same issue with TensorFlow 1.9.0

**Comment by LZaltius** [comment]
same issue with tf 1.11.0

**Comment by dpmerrell** [comment]
And 1.12.0 today.

It seems like newcomers should learn TensorFlow Probability/Edward2 rather than Edward 1, even though there's no mention of it on the Edward website.

**Comment by janosh** [comment]
> It seems like newcomers should learn TensorFlow Probability/Edward2 rather than Edward 1, even though there's no mention of it on the Edward website.

This should definitely be advised on the [Edward website](http://edwardlib.org).

**Comment by fjssharpsword** [comment]
My solution is :
1)find file: edward/util/random_variables.py
2)replace the import line:
from tensorflow.python.framework.ops import set_shape_and_handle_data_for_outputs as set_shapes_for_outputs
It works.

**Comment by felipefmoreira** [comment]
@fjssharpsword indeed, it worked.

**Comment by jihwan-jeong** [comment]
@fjssharpsword Thanks! It worked :D
