### ISSUE TITLE
ImportError: cannot import name 'set_shapes_for_outputs'

### ISSUE THREAD

**Issue by deehzee** [blei-lab/edward#916]
Installed package `edward=1.35` (and `tensorflow=1.9.0`). Importing it in python gives `ImportError`:

```
$ python -c 'import edward'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/djn/anaconda3/envs/myra3/lib/python3.6/site-packages/edward/__init__.py", line 5, in <module>
    from edward import criticisms
  File "/Users/djn/anaconda3/envs/myra3/lib/python3.6/site-packages/edward/criticisms/__init__.py", line 7, in <module>
    from edward.criticisms.evaluate import *
  File "/Users/djn/anaconda3/envs/myra3/lib/python3.6/site-packages/edward/criticisms/evaluate.py", line 10, in <module>
    from edward.util import check_data, get_session, compute_multinomial_mode, \
  File "/Users/djn/anaconda3/envs/myra3/lib/python3.6/site-packages/edward/util/__init__.py", line 10, in <module>
    from edward.util.random_variables import *
  File "/Users/djn/anaconda3/envs/myra3/lib/python3.6/site-packages/edward/util/random_variables.py", line 15, in <module>
    from tensorflow.python.framework.ops import set_shapes_for_outputs
ImportError: cannot import name 'set_shapes_for_outputs'
```

**Comment by sadatnfs** [comment]
It's an ongoing issue with many other issues opened. TF changed their API and Edward still builds upon an older version

**Comment by 08zhangyi** [comment]
You can see the problem #893[https://github.com/blei-lab/edward/issues/893](url)
