### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by spjohn** [blei-lab/edward#918]
import edward is giving Import Error.
ImportError: cannot import name 'set_shapes_for_outputs'

**Comment by gowthamasu** [comment]
from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gowth\Anaconda3\envs\py36\lib\site-packages\edward\__init__.py", line 5, in <module>
    from edward import criticisms
  File "C:\Users\gowth\Anaconda3\envs\py36\lib\site-packages\edward\criticisms\__init__.py", line 7, in <module>
    from edward.criticisms.evaluate import *
  File "C:\Users\gowth\Anaconda3\envs\py36\lib\site-packages\edward\criticisms\evaluate.py", line 10, in <module>
    from edward.util import check_data, get_session, compute_multinomial_mode, \
  File "C:\Users\gowth\Anaconda3\envs\py36\lib\site-packages\edward\util\__init__.py", line 10, in <module>
    from edward.util.random_variables import *
  File "C:\Users\gowth\Anaconda3\envs\py36\lib\site-packages\edward\util\random_variables.py", line 15, in <module>
    from tensorflow.python.framework.ops import set_shapes_for_outputs
ImportError: cannot import name 'set_shapes_for_outputs'

**Comment by jamesbsilva** [comment]
Same here

**Comment by liuchenbaidu** [comment]
>>> import edward
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liuchen/anaconda3/lib/python3.6/site-packages/edward/__init__.py", line 5, in <module>
    from edward import criticisms
  File "/home/liuchen/anaconda3/lib/python3.6/site-packages/edward/criticisms/__init__.py", line 7, in <module>
    from edward.criticisms.evaluate import *
  File "/home/liuchen/anaconda3/lib/python3.6/site-packages/edward/criticisms/evaluate.py", line 10, in <module>
    from edward.util import check_data, get_session, compute_multinomial_mode, \
  File "/home/liuchen/anaconda3/lib/python3.6/site-packages/edward/util/__init__.py", line 10, in <module>
    from edward.util.random_variables import *
  File "/home/liuchen/anaconda3/lib/python3.6/site-packages/edward/util/random_variables.py", line 15, in <module>
    from tensorflow.python.framework.ops import set_shapes_for_outputs
ImportError: cannot import name 'set_shapes_for_outputs'

**Comment by gowthamasu** [comment]
I downgraded tf version to required specifications, it is working now. It's tf version 1.2.0

**Comment by xixi9** [comment]
first 
import tensorflow as tf
then
from edward.models import Normal

**Comment by cpoptic** [comment]
Could edward devs please be more explicit about which version of tensorflow is required to run edward?  It's frustrating and a time-sink to iterate through various TF versions trying to find the most recent version that is still compatible with Edward.

The TF API is changing rapidly, so it's hard to keep up, but even a simple requirements.txt would suffice.

**Comment by wingwingtwo** [comment]
it still does not work

> first
> import tensorflow as tf
> then
> from edward.models import Normal

**Comment by tqi2** [comment]
After tried many times with different combinations of tensorflow and edward version, I finally found the newest Edward and tensorflow 1.2.0 works!

**Comment by cymqqqq** [comment]
use google colab 
 install tf1.2.0 can solve this question
