### ISSUE TITLE
installing edward in anaconda

### ISSUE THREAD

**Issue by neuronphysics** [blei-lab/edward#942]
I have been trying to install `tensorflow` and `edward` on my macos laptop and I failed following all the recipes in the web. This is how I installed edward and tensorflow
```
conda create -n tf_env python=3.6
conda activate tf_env
pip install --ignore-installed --upgrade tensorflow==2.0.0
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
pip install edward
```
Here I get the following errors when I import edward
```
>>> import tensorflow
>>> import edward
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anaconda2/lib/python2.7/site-packages/edward/__init__.py", line 5, in <module>
    from edward import criticisms
  File "/Users/anaconda2/lib/python2.7/site-packages/edward/criticisms/__init__.py", line 7, in <module>
    from edward.criticisms.evaluate import *
  File "/Users/anaconda2/lib/python2.7/site-packages/edward/criticisms/evaluate.py", line 9, in <module>
    from edward.models import RandomVariable
  File "/Users/anaconda2/lib/python2.7/site-packages/edward/models/__init__.py", line 7, in <module>
    from edward.models.dirichlet_process import *
  File "/Users/anaconda2/lib/python2.7/site-packages/edward/models/dirichlet_process.py", line 8, in <module>
    from tensorflow.contrib.distributions import Distribution
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distributions
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 34, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/Users/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/Users/anaconda2/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/Users/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/Users/anaconda2/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/Users/anaconda2/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/Users/anaconda2/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'
```
Any suggestion why did I get this errors?
Thanks

**Comment by hyeon424** [comment]
Do you have to use version 2.0.0 of tensorflow?
I'm using edward well with the following version.
tensorflow==1.2.0rc0
